# Generated by Django 5.2.5 on 2025-09-09 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0004_alter_lista_colaboradores_correo'),
        ('ips', '0009_alter_historial_acciones_fecha_realizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='faltantes_inventario_hardware',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ips.lista_ips', to_field='ip')),
                ('nombre_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.lista_colaboradores', to_field='nombre_colaborador')),
            ],
            options={
                'db_table': 'faltantes_inventario_hardware',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='inventario_hardware',
            fields=[
                ('id_inventario_h', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=60, null=True)),
                ('procesador', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=6, null=True)),
                ('video_integrada', models.CharField(blank=True, max_length=100, null=True)),
                ('video_dedicada', models.CharField(blank=True, max_length=100, null=True)),
                ('so', models.CharField(blank=True, max_length=20, null=True)),
                ('almacenamiento', models.CharField(blank=True, max_length=200, null=True)),
                ('puertas_enlace', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ips.lista_ips', to_field='ip')),
                ('nombre_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.lista_colaboradores', to_field='nombre_colaborador')),
            ],
            options={
                'db_table': 'inventario_hardware',
                'ordering': ['id_inventario_h'],
            },
        ),
    ]
