# Generated by Django 5.2.5 on 2025-09-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0004_alter_lista_colaboradores_correo'),
        ('ips', '0009_alter_historial_acciones_fecha_realizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='faltantes_backup_informacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ips.lista_ips', to_field='ip')),
                ('nombre_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.lista_colaboradores', to_field='nombre_colaborador')),
            ],
            options={
                'db_table': 'faltantes_backup_informacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='lista_backups_informacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=50)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ips.lista_ips')),
                ('nombre_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.lista_colaboradores')),
            ],
            options={
                'db_table': 'lista_backups_informacion',
                'ordering': ['id'],
            },
        ),
    ]
