# Generated by Django 5.2.5 on 2025-09-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkinformacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_backups_informacion',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
    ]
