# Generated by Django 5.2.5 on 2025-08-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_estado_ips',
            fields=[
                ('codigo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=40)),
                ('descripcion_estado', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipo_estado_ips',
            },
        ),
        migrations.CreateModel(
            name='lista_ips',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('codigo_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ips.tipo_estado_ips')),
            ],
            options={
                'db_table': 'lista_ips',
                'ordering': ['id'],
            },
        ),
    ]
