# Generated by Django 5.2.5 on 2025-09-03 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='niveles_firewall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(max_length=50, unique=True)),
                ('descripcion_nivel', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'niveles_firewall',
            },
        ),
        migrations.CreateModel(
            name='oficinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_oficina', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'oficinas',
            },
        ),
        migrations.CreateModel(
            name='tipo_equipos_informaticos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_equipo', models.CharField(max_length=50, unique=True)),
                ('descripcion_tipo_equipo', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'tipo_equipos_informaticos',
            },
        ),
        migrations.CreateModel(
            name='tipo_estado_ips',
            fields=[
                ('codigo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=40, unique=True)),
                ('descripcion_estado', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipo_estado_ips',
            },
        ),
        migrations.CreateModel(
            name='tipo_secciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_seccion', models.CharField(max_length=50, unique=True)),
                ('descripcion_seccion', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'tipo_secciones',
            },
        ),
        migrations.CreateModel(
            name='lista_ips',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('marca_equipo', models.CharField(default='Generico', max_length=120)),
                ('modelo_equipo', models.CharField(default='Generico', max_length=120)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('ip_nivel_firewall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.niveles_firewall', to_field='nombre_nivel')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.oficinas', to_field='nombre_oficina')),
                ('tipo_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.tipo_equipos_informaticos', to_field='nombre_tipo_equipo')),
                ('codigo_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.tipo_estado_ips', to_field='nombre_estado')),
                ('ip_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.tipo_secciones', to_field='nombre_seccion')),
            ],
            options={
                'db_table': 'lista_ips',
                'ordering': ['id'],
            },
        ),
    ]
