# Generated by Django 5.2.5 on 2025-09-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_ips',
            name='marca_equipo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='lista_ips',
            name='modelo_equipo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
