# Generated by Django 5.2.5 on 2025-09-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='niveles_firewall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(max_length=50, unique=True)),
                ('descripcion_nivel', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'niveles_firewall',
            },
        ),
        migrations.CreateModel(
            name='oficinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_oficina', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'oficinas',
            },
        ),
        migrations.CreateModel(
            name='tipo_equipos_informaticos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_equipo', models.CharField(max_length=50, unique=True)),
                ('descripcion_tipo_equipo', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'tipo_equipos_informaticos',
            },
        ),
        migrations.CreateModel(
            name='tipo_secciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_seccion', models.CharField(max_length=50, unique=True)),
                ('descripcion_seccion', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'tipo_secciones',
            },
        ),
        migrations.AddField(
            model_name='lista_ips',
            name='marca_equipo',
            field=models.CharField(default='Generico', max_length=120),
        ),
        migrations.AddField(
            model_name='lista_ips',
            name='modelo_equipo',
            field=models.CharField(default='Generico', max_length=120),
        ),
        migrations.AlterField(
            model_name='lista_ips',
            name='codigo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.tipo_estado_ips', to_field='nombre_estado'),
        ),
        migrations.AlterField(
            model_name='tipo_estado_ips',
            name='nombre_estado',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='lista_ips',
            name='ip_nivel_firewall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.niveles_firewall', to_field='nombre_nivel'),
        ),
        migrations.AddField(
            model_name='lista_ips',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.oficinas', to_field='nombre_oficina'),
        ),
        migrations.AddField(
            model_name='lista_ips',
            name='tipo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.tipo_equipos_informaticos', to_field='nombre_tipo_equipo'),
        ),
        migrations.AddField(
            model_name='lista_ips',
            name='ip_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.tipo_secciones', to_field='nombre_seccion'),
        ),
    ]
