# Generated by Django 5.2.5 on 2025-09-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0002_alter_lista_ips_marca_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_ips',
            name='codigo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.tipo_estado_ips'),
        ),
    ]
