# Generated by Django 5.2.5 on 2025-09-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0003_alter_lista_ips_codigo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_ips',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
