# Generated by Django 5.2.5 on 2025-09-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0004_alter_lista_ips_id'),
    ]

    operations = [
        
    ]
