# Generated by Django 5.2.5 on 2025-09-06 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0005_alter_lista_ips_codigo_estado'),
    ]

    operations = [        
        migrations.CreateModel(
            name='historial_acciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_colaborador', models.CharField(max_length=150)),
                ('accion_realizada', models.CharField(max_length=500)),
                ('fecha_realizacion', models.DateField(auto_now=True)),
                ('ip_historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ips.lista_ips')),
            ],
            options={
                'db_table': 'historial_acciones',
                'ordering': ['id'],
            },
        ),
    ]
