# Generated by Django 5.2.5 on 2025-09-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0006_alter_lista_ips_codigo_estado_historial_acciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_acciones',
            name='accion_realizada',
            field=models.TextField(max_length=500),
        ),
    ]
