# Generated by Django 5.2.5 on 2025-09-06 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0007_alter_historial_acciones_accion_realizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_acciones',
            name='ip_historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ips.lista_ips', to_field='ip'),
        ),
    ]
