# Generated by Django 5.2.5 on 2025-09-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0008_alter_historial_acciones_ip_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_acciones',
            name='fecha_realizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
