# Generated by Django 5.2.5 on 2025-09-10 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0010_alter_lista_ips_tipo_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_ips',
            name='tipo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ips.tipo_equipos_informaticos', to_field='nombre_tipo_equipo'),
        ),
    ]
