# Generated by Django 5.2.5 on 2025-09-03 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentas_forticlient',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.CharField(max_length=15, unique=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colaboradores.lista_colaboradores', to_field='nombre_colaborador')),
            ],
            options={
                'db_table': 'cuentas_forticlient',
            },
        ),
    ]
