# Generated by Django 5.2.5 on 2025-09-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentas_forticlient',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='cuentas_forticlient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
