# Generated by Django 5.2.5 on 2025-08-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_forticlient',
            name='contraseña',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
