# Generated by Django 5.2.5 on 2025-09-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cuentas_forticlient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs_actividades_celery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_creacion', models.DateTimeField(auto_now=True)),
                ('mensaje', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'logs_invetario_hardware',
                'ordering': ['tiempo_creacion'],
            },
        ),
    ]
