# Generated by Django 5.2.5 on 2025-09-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_logs_actividades_celery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs_actividades_celery',
            options={'ordering': ['id']},
        ),
    ]
