# Generated by Django 5.2.5 on 2025-09-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_logs_actividades_celery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs_actividades_celery',
            name='mensaje',
            field=models.CharField(max_length=250),
        ),
    ]
