select * from cuentas_forticlient
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(1,'incasur-user1','pREaOzQr$Oei',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(2,'incasur-user2','#ZZdWV8Hm9&q',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(3,'incasur-user3','$v4qXN5LgJ&U',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(4,'incasur-user4','AgtGWeAh!w&a',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(5,'incasur-user5','W9#MJv1hg%PT',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(6,'incasur-user6','pjHi#gt0!Nun',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(7,'incasur-user7','ksBPt^a4mc#N',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(8,'incasur-user8','1vnwzV&YVWr7',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(9,'incasur-user9','^NzWjUAtlVvr',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(10,'incasur-user10','NymW^!s#QKLU',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(11,'incasur-user11','o6P5sFMd0y*R',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(12,'incasur-user12','ZkJmjd&^KDzS',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(13,'incasur-user13','eBeA&&$CI#5D',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(14,'incasur-user14','&$@uik%yKtYv',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(15,'incasur-user15','jP8#osM^bPWA',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(16,'incasur-user16','wBdbES%HAckY',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(17,'incasur-user17','QkULsx*A8Xw$',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(18,'incasur-user18','m@mRGkPBBJFc',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(19,'incasur-user19','b8MGjbTk7K@r',CURRENT_DATE);
INSERT INTO cuentas_forticlient (id,usuario,contraseña,fecha_modificacion)values(20,'incasur-libre','#SrlgBAbAyc%',CURRENT_DATE);


select * from lista_ips order by id asc
--delete from lista_ips
select * from lista_ips where codigo_estado_id = 2
update lista_ips set codigo_estado_id = 2 where id =1  
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(1,'192.168.1.1',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(2,'192.168.1.2',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(3,'192.168.1.3',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(4,'192.168.1.4',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(5,'192.168.1.5',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(6,'192.168.1.6',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(7,'192.168.1.7',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(8,'192.168.1.8',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(9,'192.168.1.9',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(10,'192.168.1.10',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(11,'192.168.1.11',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(12,'192.168.1.12',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(13,'192.168.1.13',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(14,'192.168.1.14',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(15,'192.168.1.15',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(16,'192.168.1.16',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(17,'192.168.1.17',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(18,'192.168.1.18',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(19,'192.168.1.19',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(20,'192.168.1.20',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(21,'192.168.1.21',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(22,'192.168.1.22',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(23,'192.168.1.23',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(24,'192.168.1.24',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(25,'192.168.1.25',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(26,'192.168.1.26',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(27,'192.168.1.27',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(28,'192.168.1.28',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(29,'192.168.1.29',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(30,'192.168.1.30',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(31,'192.168.1.31',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(32,'192.168.1.32',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(33,'192.168.1.33',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(34,'192.168.1.34',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(35,'192.168.1.35',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(36,'192.168.1.36',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(37,'192.168.1.37',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(38,'192.168.1.38',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(39,'192.168.1.39',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(40,'192.168.1.40',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(41,'192.168.1.41',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(42,'192.168.1.42',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(43,'192.168.1.43',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(44,'192.168.1.44',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(45,'192.168.1.45',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(46,'192.168.1.46',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(47,'192.168.1.47',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(48,'192.168.1.48',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(49,'192.168.1.49',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(50,'192.168.1.50',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(51,'192.168.1.51',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(52,'192.168.1.52',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(53,'192.168.1.53',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(54,'192.168.1.54',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(55,'192.168.1.55',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(56,'192.168.1.56',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(57,'192.168.1.57',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(58,'192.168.1.58',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(59,'192.168.1.59',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(60,'192.168.1.60',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(61,'192.168.1.61',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(62,'192.168.1.62',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(63,'192.168.1.63',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(64,'192.168.1.64',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(65,'192.168.1.65',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(66,'192.168.1.66',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(67,'192.168.1.67',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(68,'192.168.1.68',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(69,'192.168.1.69',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(70,'192.168.1.70',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(71,'192.168.1.71',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(72,'192.168.1.72',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(73,'192.168.1.73',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(74,'192.168.1.74',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(75,'192.168.1.75',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(76,'192.168.1.76',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(77,'192.168.1.77',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(78,'192.168.1.78',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(79,'192.168.1.79',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(80,'192.168.1.80',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(81,'192.168.1.81',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(82,'192.168.1.82',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(83,'192.168.1.83',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(84,'192.168.1.84',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(85,'192.168.1.85',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(86,'192.168.1.86',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(87,'192.168.1.87',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(88,'192.168.1.88',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(89,'192.168.1.89',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(90,'192.168.1.90',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(91,'192.168.1.91',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(92,'192.168.1.92',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(93,'192.168.1.93',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(94,'192.168.1.94',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(95,'192.168.1.95',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(96,'192.168.1.96',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(97,'192.168.1.97',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(98,'192.168.1.98',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(99,'192.168.1.99',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(100,'192.168.1.100',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(101,'192.168.1.101',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(102,'192.168.1.102',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(103,'192.168.1.103',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(104,'192.168.1.104',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(105,'192.168.1.105',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(106,'192.168.1.106',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(107,'192.168.1.107',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(108,'192.168.1.108',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(109,'192.168.1.109',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(110,'192.168.1.110',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(111,'192.168.1.111',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(112,'192.168.1.112',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(113,'192.168.1.113',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(114,'192.168.1.114',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(115,'192.168.1.115',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(116,'192.168.1.116',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(117,'192.168.1.117',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(118,'192.168.1.118',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(119,'192.168.1.119',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(120,'192.168.1.120',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(121,'192.168.1.121',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(122,'192.168.1.122',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(123,'192.168.1.123',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(124,'192.168.1.124',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(125,'192.168.1.125',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(126,'192.168.1.126',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(127,'192.168.1.127',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(128,'192.168.1.128',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(129,'192.168.1.129',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(130,'192.168.1.130',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(131,'192.168.1.131',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(132,'192.168.1.132',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(133,'192.168.1.133',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(134,'192.168.1.134',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(135,'192.168.1.135',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(136,'192.168.1.136',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(137,'192.168.1.137',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(138,'192.168.1.138',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(139,'192.168.1.139',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(140,'192.168.1.140',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(141,'192.168.1.141',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(142,'192.168.1.142',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(143,'192.168.1.143',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(144,'192.168.1.144',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(145,'192.168.1.145',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(146,'192.168.1.146',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(147,'192.168.1.147',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(148,'192.168.1.148',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(149,'192.168.1.149',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(150,'192.168.1.150',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(151,'192.168.1.151',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(152,'192.168.1.152',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(153,'192.168.1.153',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(154,'192.168.1.154',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(155,'192.168.1.155',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(156,'192.168.1.156',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(157,'192.168.1.157',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(158,'192.168.1.158',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(159,'192.168.1.159',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(160,'192.168.1.160',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(161,'192.168.1.161',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(162,'192.168.1.162',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(163,'192.168.1.163',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(164,'192.168.1.164',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(165,'192.168.1.165',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(166,'192.168.1.166',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(167,'192.168.1.167',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(168,'192.168.1.168',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(169,'192.168.1.169',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(170,'192.168.1.170',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(171,'192.168.1.171',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(172,'192.168.1.172',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(173,'192.168.1.173',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(174,'192.168.1.174',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(175,'192.168.1.175',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(176,'192.168.1.176',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(177,'192.168.1.177',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(178,'192.168.1.178',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(179,'192.168.1.179',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(180,'192.168.1.180',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(181,'192.168.1.181',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(182,'192.168.1.182',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(183,'192.168.1.183',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(184,'192.168.1.184',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(185,'192.168.1.185',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(186,'192.168.1.186',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(187,'192.168.1.187',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(188,'192.168.1.188',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(189,'192.168.1.189',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(190,'192.168.1.190',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(191,'192.168.1.191',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(192,'192.168.1.192',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(193,'192.168.1.193',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(194,'192.168.1.194',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(195,'192.168.1.195',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(196,'192.168.1.196',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(197,'192.168.1.197',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(198,'192.168.1.198',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(199,'192.168.1.199',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(200,'192.168.1.200',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(201,'192.168.1.201',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(202,'192.168.1.202',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(203,'192.168.1.203',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(204,'192.168.1.204',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(205,'192.168.1.205',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(206,'192.168.1.206',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(207,'192.168.1.207',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(208,'192.168.1.208',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(209,'192.168.1.209',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(210,'192.168.1.210',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(211,'192.168.1.211',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(212,'192.168.1.212',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(213,'192.168.1.213',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(214,'192.168.1.214',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(215,'192.168.1.215',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(216,'192.168.1.216',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(217,'192.168.1.217',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(218,'192.168.1.218',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(219,'192.168.1.219',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(220,'192.168.1.220',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(221,'192.168.1.221',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(222,'192.168.1.222',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(223,'192.168.1.223',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(224,'192.168.1.224',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(225,'192.168.1.225',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(226,'192.168.1.226',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(227,'192.168.1.227',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(228,'192.168.1.228',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(229,'192.168.1.229',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(230,'192.168.1.230',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(231,'192.168.1.231',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(232,'192.168.1.232',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(233,'192.168.1.233',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(234,'192.168.1.234',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(235,'192.168.1.235',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(236,'192.168.1.236',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(237,'192.168.1.237',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(238,'192.168.1.238',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(239,'192.168.1.239',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(240,'192.168.1.240',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(241,'192.168.1.241',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(242,'192.168.1.242',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(243,'192.168.1.243',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(244,'192.168.1.244',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(245,'192.168.1.245',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(246,'192.168.1.246',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(247,'192.168.1.247',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(248,'192.168.1.248',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(249,'192.168.1.249',CURRENT_DATE);
INSERT INTO lista_ips (id,ip,fecha_modificacion) values(250,'192.168.1.250',CURRENT_DATE);


select * from niveles_firewall
insert into niveles_firewall (id,nombre_nivel,descripcion_nivel) values(1,'Nivel 1','Ips con acceso a todas las paginas segun la politica');
insert into niveles_firewall (id,nombre_nivel,descripcion_nivel) values(2,'Nivel 2','Ips con acceso a ciertas paginas segun la politica');
insert into niveles_firewall (id,nombre_nivel,descripcion_nivel) values(3,'Nivel 3','Ips con acceso restringido minimo');
insert into niveles_firewall (id,nombre_nivel,descripcion_nivel) values(4,'Reloj Control','Ips reservada para marcadores de asistencia');
insert into niveles_firewall (id,nombre_nivel,descripcion_nivel) values(5,'Servidores','Ips reservada para servidores');
insert into niveles_firewall (id,nombre_nivel,descripcion_nivel) values(6,'Switches','Ips reservada para servidores');
insert into niveles_firewall (id,nombre_nivel,descripcion_nivel) values(7,'CCTV','Ips reservada para camaras de seguridad');
insert into niveles_firewall (id,nombre_nivel,descripcion_nivel) values(8,'Impresoras','Ips reservada para impresoras IP');

select * from oficinas
insert into oficinas (id,nombre_oficina) values(1,'Principal-Primer Piso');
insert into oficinas (id,nombre_oficina) values(2,'Principal-Segundo Piso');
insert into oficinas (id,nombre_oficina) values(3,'Principal-Tercer Piso');
insert into oficinas (id,nombre_oficina) values(4,'Principal-Cuarto Piso');
insert into oficinas (id,nombre_oficina) values(5,'Principal-Sotano');

select * from tipo_equipos_informaticos
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (1,'Laptop','Laptop de cualquier marca');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (2,'PC','Pc de escritorio de cualquier marca');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (3,'NVR','Equipo de camaras NVR');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (4,'DVR','Equipo de camaras DVR');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (5,'Camara','Camaras IPs en ubicadas en la Lan');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (6,'Fortigate','Firewall de la empresa');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (7,'Central Telefonica','Central de anexos internos y externos');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (8,'Gateway Telefonico','Puerta de enlace para los telefonos');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (9,'Impresora','Impresoras dentro de la empresa');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (10,'Reloj Control','Relojes para el control de asistencia del personal');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (11,'Servidor Fisico','Servidores fisicos instalados');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (12,'Servidor Virutal','Servidores virutales instalados');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (13,'Switch','Switches administrables de la red');
insert into tipo_equipos_informaticos (id,nombre_tipo_equipo, descripcion_tipo_equipo) values (14,'Acces Point','Equipos para brindar wifi en la empresa');

select * from tipo_estado_ips
insert into tipo_estado_ips (codigo_estado,nombre_estado,descripcion_estado) values(1,'Ocupada','Ip fue asignada a un equipo informatico');
insert into tipo_estado_ips (codigo_estado,nombre_estado,descripcion_estado) values(2,'Libre','Ip NO fue asignada a un equipo informatico');
insert into tipo_estado_ips (codigo_estado,nombre_estado,descripcion_estado) values(3,'Sin Nivel','Ip no esta disponible para acceso a internet');

select * from tipo_secciones

insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(1,'Auditoria','Ips asignadas a Auditoria.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(2,'Contabilidad','Ips asignadas a Contabilidad.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(3,'Gerencia General','Ips asignadas a Gerencia General.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(4,'Legal','Ips asignadas a el Area Legal.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(5,'Marketing','Ips asignadas a Marketing.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(6,'Negocios','Ips asignadas a Negocios.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(7,'Operaciones','Ips asignadas a Operaciones.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(8,'OYM','Ips asignadas a Organizacion y Metodos.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(9,'Planeamiento','Ips asignadas a Planeamiento.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(10,'Recuperaciones','Ips asignadas a Recuperaciones.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(11,'Riesgos','Ips asignadas a Riesgos.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(12,'TI','Ips asignadas a Tecnologia e Informacion.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(13,'TI-CCTV','Ips asignadas a Tecnologia e Informacion Camaras.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(14,'TI-DataCenter','Ips asignadas a Tecnologia e Informacion Centro de datos.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(15,'TI-Impresoras','Ips asignadas a Tecnologia e Informacion Impresoras.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(16,'TI-Redes','Ips asignadas a Tecnologia e Informacion Switches, acces point,etc.');
insert into tipo_secciones (id,nombre_seccion,descripcion_seccion) values(17,'TI-Reloj Control','Ips asignadas a Tecnologia e Informacion Marcacion de asistencia.');

select * from estado_colaboradores
insert into estado_colaboradores (codigo_estado,nombre_estado) values(1,'Activo');
insert into estado_colaboradores (codigo_estado,nombre_estado) values(2,'Cesado');

select * from lista_ips

select *,(select nombre_colaborador from lista_colaboradores as c where c.ip_colaborador_id = i.ip and c.estado_colaboradores_id = 1) as nombre_colaborador from lista_ips as i order by id asc
select * from lista_colaboradores

select *from lista_colaboradores
delete from lista_colaboradores

select * from tipo_software

insert into tipo_software (nombre_tipo,descripcion_tipo) values('Office','Suites de Offices para editar documentos');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('Acceso Remoto','Software para acceso a equipo de forma remota');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('Editores Texto','Software para editar texto');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('Base de datos','Software para usar base de datos');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('PDF','Software para ver y editar pdfs');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('FTIA','Software para el uso del sistema FTIA');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('Impresoras','Software control de impresoras');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('Navegadores','Software para navegar por internet');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('Compresores','Software para comprimir archivos');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('Drivers','Drivers para el hardware del equipo');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('Drive','Software para drive de informacion en la nube');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('TI','Software especial permitido para el area de TI');
insert into tipo_software (nombre_tipo,descripcion_tipo) values('Otros','Otro tipo de software no considerado en categorias existentes');