# Generated by Django 5.2.5 on 2025-09-03 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_colaboradores',
            fields=[
                ('codigo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado_colaboradores',
            },
        ),
        migrations.CreateModel(
            name='lista_colaboradores',
            fields=[
                ('codigo_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_colaborador', models.CharField(max_length=150, unique=True)),
                ('usuario_sistema', models.CharField(default='SIN ACCESO AL SISTEMAS', max_length=25, unique=True)),
                ('correo', models.CharField(default='SIN CORREO', max_length=20, unique=True)),
                ('usuario_sentinel', models.CharField(default='SIN SENTINEL', max_length=15, unique=True)),
                ('usuario_sbs', models.CharField(default='SIN SBS', max_length=15, unique=True)),
                ('codigo_impresion_colaborador', models.CharField(max_length=20, unique=True)),
                ('cargo_colaborador', models.CharField(max_length=70)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado_colaboradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.estado_colaboradores')),
                ('ip_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ips.lista_ips', to_field='ip')),
            ],
            options={
                'db_table': 'lista_colaboradores',
            },
        ),
    ]
