# Generated by Django 5.2.5 on 2025-09-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_colaboradores',
            name='correo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
