# Generated by Django 5.2.5 on 2025-09-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista_colaboradores',
            old_name='puesto_colaborador',
            new_name='cargo_colaborador',
        ),
        migrations.AddField(
            model_name='lista_colaboradores',
            name='correo',
            field=models.CharField(default='SIN CORREO', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='lista_colaboradores',
            name='usuario_sbs',
            field=models.CharField(default='SIN SBS', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='lista_colaboradores',
            name='usuario_sentinel',
            field=models.CharField(default='SIN SENTINEL', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='lista_colaboradores',
            name='usuario_sistema',
            field=models.CharField(default='SIN ACCESO AL SISTEMAS', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='lista_colaboradores',
            name='codigo_impresion_colaborador',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
