# Generated by Django 5.2.5 on 2025-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_alter_lista_colaboradores_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_colaboradores',
            name='usuario_sistema',
            field=models.CharField(default='SIN ACCESO AL SISTEMA', max_length=25, unique=True),
        ),
    ]
