# Generated by Django 5.2.5 on 2025-09-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_rename_puesto_colaborador_lista_colaboradores_cargo_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_colaboradores',
            name='usuario_sistema',
            field=models.CharField(default='SIN ACCESO AL SISTEMAS', max_length=25, unique=True),
        ),
    ]
