# Generated by Django 5.2.5 on 2025-09-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_alter_lista_colaboradores_usuario_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_colaboradores',
            name='usuario_sentinel',
            field=models.CharField(default='SIN SENTINEL', max_length=15, unique=True),
        ),
    ]
