# Generated by Django 5.2.5 on 2025-09-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_alter_lista_colaboradores_usuario_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_colaboradores',
            name='correo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
