"""
Django settings for AdministradorTI project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from celery.schedules import crontab


load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-unp06nl8bb$-+$d@kplp3l32riq^8w$_w8_wn4qb$tttk%t7y_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','192.168.1.8','localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'colaboradores',
    'ips',
    'inventario_hardware',
    'inventario_software',
    'bkinformacion',
    'administracion_windows',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AdministradorTI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AdministradorTI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.getenv('DATABASE_SERVER'),
        'NAME': os.getenv('DATABASE_DB'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'PORT': os.getenv('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Añade esto para que Django sepa que no es el dueño de la raíz
FORCE_SCRIPT_NAME = '/admintihome'

STATIC_URL = '/admintihome/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)

#STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATIC_ROOT = '/var/www/mi_proyecto/static/'

MEDIA_URL = '/admintihome/archivos/'
#MEDIA_ROOT = os.path.join(BASE_DIR,'archivos')
MEDIA_ROOT = '/var/www/mi_proyecto/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_NAME = 'administrador_ti'
#Configuracion Celery broker
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Lima'

# 1. LIMITAR CONCURRENCIA (Crucial para el CPU)
# Obliga a Celery a usar un solo proceso worker. 
# Esto evitará que el CPU llegue al 80-90% constantemente.
CELERY_WORKER_CONCURRENCY = 1
# Configuración de Celery
# Asegura que las tareas sean reconocidas solo después de ser completadas
CELERY_TASK_ACKS_LATE = True

# Permite que los trabajadores procesen una tarea a la vez
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
#Configuracion Celery broker
# Límite de tiempo (duro) para terminar una tarea, en segundos.
# 7200 segundos = 2 horas. Esto dará margen para que el backup
# termine sin ser terminado por el worker.
CELERY_TASK_TIME_LIMIT = 43200

# Opcional: Límite de tiempo suave. Si se excede, lanza una excepción SoftTimeLimitExceeded 
# dentro de la tarea, permitiéndole limpiar conexiones o guardar progreso.
# 6000 segundos = 1 hora y 40 minutos.
CELERY_TASK_SOFT_TIME_LIMIT = 41400
#Limite de memoria ram 300MB
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 500000
CELERY_WORKER_MAX_TASKS_PER_CHILD = 10


CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 45000, 
}

CELERY_BEAT_SCHEDULE = {
    #Primera ejecucion mensual de tareas automaticas
    'inventario_hardware_9_am_2do_mes': {
        'task': 'inventario_hardware.task.ejecutar_inventario_hardware',
        'schedule': crontab(
            minute=0,
            hour=9,
            day_of_month='2',
            month_of_year='1-12'
        ),
    },
    'inventario_software_9_30_am_2do_mes': {
        'task': 'inventario_software.task.ejecutar_inventario_software',
        'schedule': crontab(
            minute=30,
            hour=9,
            day_of_month='2',
            month_of_year='1-12'
        ),
    },
    'revision_windows_usb_10_am_2do_mes': {
        'task': 'administracion_windows.task.verificacion_usb_all',
        'schedule': crontab(
            minute=0,
            hour=10,
            day_of_month='2',
            month_of_year='1-12'
        ),
    },
    'backup_de_informacion_11_am_2do_mes': {
        'task': 'bkinformacion.task.ejecutar_backup_informacion',
        'schedule': crontab(
            minute=0,
            hour=11,
            day_of_month='2',
            month_of_year='1-12'
        ),
    },
    #Ejecucion Automatica Faltantes Inicio del Mes Todos
    'faltantes_inventario_hardware': {
        'task': 'inventario_hardware.task.ejecutar_faltantes_inventario_hardware',
        'schedule': crontab(
            minute=0,
            hour='9-15',
            day_of_month='3-7',
            month_of_year='1-12'
        ),
    },
    'faltantes_inventario_software': {
        'task': 'inventario_software.task.ejecutar_faltantes_inventario_software',
        'schedule': crontab(
            minute=0,
            hour='10,16',
            day_of_month='3-7',
            month_of_year='1-12'
        ),
    },
    'faltantes_revision_windows_usb': {
        'task': 'administracion_windows.task.verificacion_usb_faltantes',
        'schedule': crontab(
            minute=0,
            hour='11,17',
            day_of_month='3-7',
            month_of_year='1-12'
        ),
    },
    'faltantes_backup_informacion': {
        'task': 'bkinformacion.task.ejecutar_faltantes_backup_informacion',
        'schedule': crontab(
            minute=0,
            hour=12,
            day_of_month='3-7',
            month_of_year='1-12'
        ),
    },
    #Ejecucion Automatica Faltantes Fin del Mes Todos
    'faltantes_inventario_hardware': {
        'task': 'inventario_hardware.task.ejecutar_faltantes_inventario_hardware',
        'schedule': crontab(
            minute=0,
            hour='9-15',
            day_of_month='25-28',
            month_of_year='1-12'
        ),
    },
    'faltantes_inventario_software': {
        'task': 'inventario_software.task.ejecutar_faltantes_inventario_software',
        'schedule': crontab(
            minute=0,
            hour='10,16',
            day_of_month='25-28',
            month_of_year='1-12'
        ),
    },
    'faltantes_revision_windows_usb': {
        'task': 'administracion_windows.task.verificacion_usb_faltantes',
        'schedule': crontab(
            minute=0,
            hour='11,17',
            day_of_month='25-28',
            month_of_year='1-12'
        ),
    },
    'faltantes_backup_informacion': {
        'task': 'bkinformacion.task.ejecutar_faltantes_backup_informacion',
        'schedule': crontab(
            minute=0,
            hour=12,
            day_of_month='25-28',
            month_of_year='1-12'
        ),
    },
    #Asistencia
    'asistencia_entrada_L_V': {
        'task': 'administracion_windows.task.marcar_entrada',
        'schedule': crontab(
            minute=0,
            hour=19,
            day_of_month='*',
            month_of_year='1-12'
        ),
    },
    'asistencia_entrada_S': {
        'task': 'administracion_windows.task.marcar_entrada',
        'schedule': crontab(
            minute=0,
            hour=13,
            day_of_month='*',
            month_of_year='1-12'
        ),
    },
    'asistencia_salida_L_V': {
        'task': 'administracion_windows.task.marcar_salida',
        'schedule': crontab(
            minute=0,
            hour=21,
            day_of_month='*',
            month_of_year='1-12'
        ),
    },
    'asistencia_salida_S': {
        'task': 'administracion_windows.task.marcar_salida',
        'schedule': crontab(
            minute=45,
            hour=16,
            day_of_month='*',
            month_of_year='1-12'
        ),
    },
    'enviar_archivos_efact': {
        'task': 'administracion_windows.task.enviar_efact',
        'schedule': crontab(
            minute=26,
            hour=9,
            day_of_month='*',
            month_of_year='1-12'
        ),
    },
    # Segunda regla: A las 5:00 PM
    
    #'tarea_prueba': {
    #   'task': 'administracion_windows.task.marcar_salida',
    #    'schedule': crontab(
    #        minute=40,
    #        hour=10,
    #        day_of_month='*',
    #       month_of_year='1-12'
    #   ),
    #},
}