# Generated by Django 5.2.5 on 2025-09-10 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0004_alter_lista_colaboradores_correo'),
        ('ips', '0009_alter_historial_acciones_fecha_realizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_software',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=20)),
                ('descripcion_tipo', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'tipo_software',
            },
        ),
        migrations.CreateModel(
            name='faltantes_inventario_software',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ips.lista_ips')),
                ('nombre_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.lista_colaboradores', to_field='nombre_colaborador')),
            ],
            options={
                'db_table': 'faltantes_inventario_software',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='inventario_software',
            fields=[
                ('id_inventario_s', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_software', models.CharField(max_length=40)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ips.lista_ips', to_field='ip')),
                ('tipo_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_software.tipo_software')),
            ],
            options={
                'db_table': 'inventario_software',
                'ordering': ['id_inventario_s'],
            },
        ),
    ]
